In [1]:
import pandas as pd
import numpy as np

In [25]:
df=pd.read_csv('mercedesbenz.csv',usecols=['X1','X2','X3','X4','X5','X6'])
df.head(10)

  X1  X2 X3 X4 X5 X6
0  v  at  a  d  u  j
1  t  av  e  d  y  l
2  w   n  c  d  x  j
3  t   n  f  d  x  l
4  v   n  f  d  h  d
5  b   e  c  d  g  h
6  r   e  f  d  f  h
7  l  as  f  d  f  j
8  s  as  e  d  f  i
9  b  aq  c  d  f  a

### checking the unique categories present in each column

In [24]:
for col in df:
    print(col,':',len(df[col].unique()),'labels')

X1 : 27 labels
X2 : 44 labels
X3 : 7 labels
X4 : 4 labels
X5 : 29 labels
X6 : 12 labels
aa : 2 labels
s : 2 labels
b : 2 labels
l : 2 labels
v : 2 labels
r : 2 labels
i : 2 labels
a : 2 labels
c : 2 labels
o : 2 labels
X1_aa : 2 labels
X1_s : 2 labels
X1_b : 2 labels
X1_l : 2 labels
X1_v : 2 labels
X1_r : 2 labels
X1_i : 2 labels
X1_a : 2 labels
X1_c : 2 labels
X1_o : 2 labels
X2_as : 2 labels
X2_ae : 2 labels
X2_ai : 2 labels
X2_m : 2 labels
X2_ak : 2 labels
X2_r : 2 labels
X2_n : 2 labels
X2_s : 2 labels
X2_f : 2 labels
X2_e : 2 labels
X3_c : 2 labels
X3_f : 2 labels
X3_a : 2 labels
X3_d : 2 labels
X3_g : 2 labels
X3_e : 2 labels
X3_b : 2 labels

In [9]:
pd.get_dummies(df,drop_first=True)

,X1_aa,X1_ab,X1_b,X1_c,X1_d,X1_e,X1_f,X1_g,X1_h,X1_i,...,X6_c,X6_d,X6_e,X6_f,X6_g,X6_h,X6_i,X6_j,X6_k,X6_l
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4205,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4206,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4207,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4208,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

## checking the top 10 categories in X1 column

In [5]:
df.X1.value_counts().head(10)

aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
Name: X1, dtype: int64

## making a list of these top 10 categories

In [27]:
top10=[i for i in df.X1.value_counts().head(10).index]
top10

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

## applying the technique of converting these top categories into binary

In [13]:
for label in top10:
    df[label]=np.where(df['X1']==label,1,0)
df[['X1']+top10].head(20)

    X1  aa  s  b  l  v  r  i  a  c  o
0    v   0  0  0  0  1  0  0  0  0  0
1    t   0  0  0  0  0  0  0  0  0  0
2    w   0  0  0  0  0  0  0  0  0  0
3    t   0  0  0  0  0  0  0  0  0  0
4    v   0  0  0  0  1  0  0  0  0  0
5    b   0  0  1  0  0  0  0  0  0  0
6    r   0  0  0  0  0  1  0  0  0  0
7    l   0  0  0  1  0  0  0  0  0  0
8    s   0  1  0  0  0  0  0  0  0  0
9    b   0  0  1  0  0  0  0  0  0  0
10   r   0  0  0  0  0  1  0  0  0  0
11   r   0  0  0  0  0  1  0  0  0  0
12   b   0  0  1  0  0  0  0  0  0  0
13   r   0  0  0  0  0  1  0  0  0  0
14   s   0  1  0  0  0  0  0  0  0  0
15   l   0  0  0  1  0  0  0  0  0  0
16   r   0  0  0  0  0  1  0  0  0  0
17  aa   1  0  0  0  0  0  0  0  0  0
18   c   0  0  0  0  0  0  0  0  1  0
19   a   0  0  0  0  0  0  0  1  0  0

## making a function to make it easy for converting it into binary for all the features

In [14]:
def on_hot(dataframe,columns,top10):
    for label in top10:
        df[columns+'_'+label]=np.where(df[columns]==label,1,0)
on_hot(df,'X1',top10)
df.head()

,X1,X2,X3,X4,X5,X6,aa,s,b,l,...,X1_aa,X1_s,X1_b,X1_l,X1_v,X1_r,X1_i,X1_a,X1_c,X1_o
0,v,at,a,d,u,j,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,t,n,f,d,x,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,v,n,f,d,h,d,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [18]:
top10=[i for i in df['X2'].value_counts().head(10).index]
print(top10)
on_hot(df,'X2',top10)
df.head()

['as', 'ae', 'ai', 'm', 'ak', 'r', 'n', 's', 'f', 'e']

,X1,X2,X3,X4,X5,X6,aa,s,b,l,...,X2_as,X2_ae,X2_ai,X2_m,X2_ak,X2_r,X2_n,X2_s,X2_f,X2_e
0,v,at,a,d,u,j,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,t,n,f,d,x,l,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,v,n,f,d,h,d,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [21]:
top10=[i for i in df['X3'].value_counts().head(10).index]
print(top10)
on_hot(df,'X3',top10)
df.head()

['c', 'f', 'a', 'd', 'g', 'e', 'b']

,X1,X2,X3,X4,X5,X6,aa,s,b,l,...,X2_s,X2_f,X2_e,X3_c,X3_f,X3_a,X3_d,X3_g,X3_e,X3_b
0,v,at,a,d,u,j,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,w,n,c,d,x,j,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,t,n,f,d,x,l,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,v,n,f,d,h,d,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

## PRACTICE AGAIN

In [28]:
df=pd.read_csv('mercedesbenz.csv',usecols=['X1','X2','X3','X4','X5','X6'])
df.head(10)

  X1  X2 X3 X4 X5 X6
0  v  at  a  d  u  j
1  t  av  e  d  y  l
2  w   n  c  d  x  j
3  t   n  f  d  x  l
4  v   n  f  d  h  d
5  b   e  c  d  g  h
6  r   e  f  d  f  h
7  l  as  f  d  f  j
8  s  as  e  d  f  i
9  b  aq  c  d  f  a

In [30]:
df.X1.nunique()

27

In [35]:
for col in df:
    print(col,':',len(df[col].unique()),'labels')

X1 : 27 labels
X2 : 44 labels
X3 : 7 labels
X4 : 4 labels
X5 : 29 labels
X6 : 12 labels

In [43]:
df.shape

(4209, 6)

In [40]:
df1=pd.get_dummies(df,drop_first=True)

    X1  X2 X3 X4 X5 X6
0    v  at  a  d  u  j
1    t  av  e  d  y  l
2    w   n  c  d  x  j
3    t   n  f  d  x  l
4    v   n  f  d  h  d
5    b   e  c  d  g  h
6    r   e  f  d  f  h
7    l  as  f  d  f  j
8    s  as  e  d  f  i
9    b  aq  c  d  f  a
10   r   r  f  d  f  h
11   r   e  f  d  f  h
12   b  ai  c  d  f  g
13   r   e  f  d  j  h
14   s  as  e  d  j  g
15   l  ak  f  d  j  d
16   r   e  f  d  j  h
17  aa  as  c  d  j  c
18   c   m  c  d  j  d
19   a  ak  f  d  j  i

In [41]:
df1.shape

(4209, 117)

In [54]:
top10=[i for i in df.X1.value_counts().head(10).index]
top10

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [65]:
for label in top10:
    df[label]=np.where(df['X1']==label,1,0)
    df[['X1']+top10].head(20)

In [74]:
df.head(20)

    X1  X2 X3 X4 X5 X6  aa  s  b  l  v  r  i  a  c  o
0    v  at  a  d  u  j   0  0  0  0  1  0  0  0  0  0
1    t  av  e  d  y  l   0  0  0  0  0  0  0  0  0  0
2    w   n  c  d  x  j   0  0  0  0  0  0  0  0  0  0
3    t   n  f  d  x  l   0  0  0  0  0  0  0  0  0  0
4    v   n  f  d  h  d   0  0  0  0  1  0  0  0  0  0
5    b   e  c  d  g  h   0  0  1  0  0  0  0  0  0  0
6    r   e  f  d  f  h   0  0  0  0  0  1  0  0  0  0
7    l  as  f  d  f  j   0  0  0  1  0  0  0  0  0  0
8    s  as  e  d  f  i   0  1  0  0  0  0  0  0  0  0
9    b  aq  c  d  f  a   0  0  1  0  0  0  0  0  0  0
10   r   r  f  d  f  h   0  0  0  0  0  1  0  0  0  0
11   r   e  f  d  f  h   0  0  0  0  0  1  0  0  0  0
12   b  ai  c  d  f  g   0  0  1  0  0  0  0  0  0  0
13   r   e  f  d  j  h   0  0  0  0  0  1  0  0  0  0
14   s  as  e  d  j  g   0  1  0  0  0  0  0  0  0  0
15   l  ak  f  d  j  d   0  0  0  1  0  0  0  0  0  0
16   r   e  f  d  j  h   0  0  0  0  0  1  0  0  0  0
17  aa  as  c  d  j  c   1  0  0  0  0  0  0  0  0  0
18   c   m  c  d  j  d   0  0  0  0  0  0  0  0  1  0
19   a  ak  f  d  j  i   0  0  0  0  0  0  0  1  0  0

In [75]:
def top_count(dataframe,col,top10):
    for label in top10:
        df[col+"_"+label]=np.where(df[col]==label,1,0)

In [76]:
top_count(df,'X1',top10)
df.head(20)

,X1,X2,X3,X4,X5,X6,aa,s,b,l,...,X1_aa,X1_s,X1_b,X1_l,X1_v,X1_r,X1_i,X1_a,X1_c,X1_o
0,v,at,a,d,u,j,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,t,n,f,d,x,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,v,n,f,d,h,d,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,b,e,c,d,g,h,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
6,r,e,f,d,f,h,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
7,l,as,f,d,f,j,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
8,s,as,e,d,f,i,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
9,b,aq,c,d,f,a,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
10,r,r,f,d,f,h,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
11,r,e,f,d,f,h,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
12,b,ai,c,d,f,g,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
13,r,e,f,d,j,h,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,s,as,e,d,j,g,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
15,l,ak,f,d,j,d,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
16,r,e,f,d,j,h,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
17,aa,as,c,d,j,c,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
18,c,m,c,d,j,d,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
19,a,ak,f,d,j,i,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [78]:
df.drop(['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o'],inplace=True,axis='columns')

In [79]:
df.head(20)

,X1,X2,X3,X4,X5,X6,X1_aa,X1_s,X1_b,X1_l,X1_v,X1_r,X1_i,X1_a,X1_c,X1_o
0,v,at,a,d,u,j,0,0,0,0,1,0,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,0,0,0,0,0,0,0,0,0,0
3,t,n,f,d,x,l,0,0,0,0,0,0,0,0,0,0
4,v,n,f,d,h,d,0,0,0,0,1,0,0,0,0,0
5,b,e,c,d,g,h,0,0,1,0,0,0,0,0,0,0
6,r,e,f,d,f,h,0,0,0,0,0,1,0,0,0,0
7,l,as,f,d,f,j,0,0,0,1,0,0,0,0,0,0
8,s,as,e,d,f,i,0,1,0,0,0,0,0,0,0,0
9,b,aq,c,d,f,a,0,0,1,0,0,0,0,0,0,0
10,r,r,f,d,f,h,0,0,0,0,0,1,0,0,0,0
11,r,e,f,d,f,h,0,0,0,0,0,1,0,0,0,0
12,b,ai,c,d,f,g,0,0,1,0,0,0,0,0,0,0
13,r,e,f,d,j,h,0,0,0,0,0,1,0,0,0,0
14,s,as,e,d,j,g,0,1,0,0,0,0,0,0,0,0
15,l,ak,f,d,j,d,0,0,0,1,0,0,0,0,0,0
16,r,e,f,d,j,h,0,0,0,0,0,1,0,0,0,0
17,aa,as,c,d,j,c,1,0,0,0,0,0,0,0,0,0
18,c,m,c,d,j,d,0,0,0,0,0,0,0,0,1,0
19,a,ak,f,d,j,i,0,0,0,0,0,0,0,1,0,0

In [81]:
top10=[i for i in df.X2.value_counts().head(10).index]
top10

['as', 'ae', 'ai', 'm', 'ak', 'r', 'n', 's', 'f', 'e']

In [87]:
top_count(df,'X2',top10)
pd.set_option('display.max_columns',30)
df.head(20)

,X1,X2,X3,X4,X5,X6,X1_aa,X1_s,X1_b,X1_l,X1_v,X1_r,X1_i,X1_a,X1_c,X1_o,X2_as,X2_ae,X2_ai,X2_m,X2_ak,X2_r,X2_n,X2_s,X2_f,X2_e
0,v,at,a,d,u,j,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,t,n,f,d,x,l,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,v,n,f,d,h,d,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
5,b,e,c,d,g,h,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
6,r,e,f,d,f,h,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7,l,as,f,d,f,j,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
8,s,as,e,d,f,i,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
9,b,aq,c,d,f,a,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,r,r,f,d,f,h,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
11,r,e,f,d,f,h,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
12,b,ai,c,d,f,g,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
13,r,e,f,d,j,h,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
14,s,as,e,d,j,g,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
15,l,ak,f,d,j,d,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
16,r,e,f,d,j,h,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
17,aa,as,c,d,j,c,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
18,c,m,c,d,j,d,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
19,a,ak,f,d,j,i,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0